### ISSUE TITLE
Selecting text is laggy

### ISSUE THREAD

**Issue by loudar** [mellodoot/arimelody.me#1]
Fix it pls

**Comment by arimelody** [comment]
~~i'm noticing a little bit of lag selecting text on chromium, though strangely i don't see this behaviour on firefox. worth having a look at, but i wouldn't know the root cause of this~~

edit: thought this was an issue for openterminal, whoops!
i don't see this issue on chromium, but *do* see it on firefox... what????

**Comment by loudar** [comment]
If the glow is done with css, it might be a slow implementation of the glow maybe or smth along those lines

**Comment by arimelody** [comment]
that would make sense if it didn't behave so differently across both pages and browser combinations... as if one thing is bogging chrome down, and one thing is bogging firefox down, but neither of them are shared?

**Comment by arimelody** [comment]
after some experimentation on both openterminal and arimelody.me, i can confirm that removing the text glow drastically improves performance on chromium.

turns out blurring lots of text across a large radius is *checks papers* not performant.

this issue can be lessened a lot by using one text-shadow at around 2em, as opposed to the current 3em + 1em stack that OT uses. i'll apply patches to both codebases!
